spring.application.name=Gmart_Full_Stack

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/gmart_db?createDatabaseIfNotExist=true
#spring.datasource.url=jdbc:mysql://bpkq02uithydeaalzc9m-mysql.services.clever-cloud.com:3306/bpkq02uithydeaalzc9m
#spring.datasource.username=upxpwjx7jrm01vzc
spring.datasource.username=root
#spring.datasource.password=Khr3wbwejNFa3UzuLJpU
spring.datasource.password=mrdio2
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# HikariCP Connection Pool settings (to stay under 5 connection limit)
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=10000
spring.datasource.hikari.keepalive-time=30000

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
# spring.main.web-application-type=none
